# -*- coding: utf-8 -*-
"""anu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16v5-ljqQ6sX0Hj6nxZLVoWxqO6SXlpe1
"""

import pandas as pd
df = pd.read_csv('D:/ANU/python/SuperMarket Analysis.csv')

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Encode categorical variables
categorical_cols = ['Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Payment']
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

# 2. Prepare features and target
X = df.drop(columns=['Unit price', 'Invoice ID', 'Date', 'Time'])
y = df['Unit price']

# 3. Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# 4. Create and train Random Forest model
rf_model = RandomForestRegressor(n_estimators=100, random_state=0)
rf_model.fit(X_train, y_train)

# 5. Make predictions
y_pred = rf_model.predict(X_test)

# 6. Enhanced model evaluation
print("\n" + "="*50)
print("Random Forest Regression Performance Metrics")
print("="*50)

# Basic metrics
print(f"\nR-squared Score: {r2_score(y_test, y_pred):.4f} (0-1, higher is better)")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred):.4f} (in unit price units)")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred):.4f}")
print(f"Root Mean Squared Error: {np.sqrt(mean_squared_error(y_test, y_pred)):.4f}")

# Percentage-based accuracy metrics
mape = np.mean(np.abs((y_test - y_pred) / (y_test + 1e-10))) * 100
accuracy = 100 - mape

print(f"\nMean Absolute Percentage Error: {mape:.2f}%")
print(f"Approximate Accuracy: {accuracy:.2f}% (100 - MAPE)")

# Residual analysis
residuals = y_test - y_pred
print(f"\nResidual Analysis:")
print(f"Min residual: {residuals.min():.4f}")
print(f"Max residual: {residuals.max():.4f}")
print(f"Average residual: {residuals.mean():.4f}")

# Feature importance
print(f"\nTop 5 Important Features:")
feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': rf_model.feature_importances_
}).sort_values('importance', ascending=False)

print(feature_importance.head(5))

# 7. Add Visualizations
print("\n" + "="*50)
print("Visualizations")
print("="*50)

# Plot Actual vs. Predicted Values
plt.figure(figsize=(10, 6))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], '--r', linewidth=2)
plt.title('Actual vs. Predicted Unit Price')
plt.xlabel('Actual Unit Price')
plt.ylabel('Predicted Unit Price')
plt.grid(True)
plt.show()

# Plot Residuals Distribution
plt.figure(figsize=(10, 6))
sns.histplot(residuals, kde=True)
plt.title('Distribution of Residuals')
plt.xlabel('Residuals (Actual - Predicted)')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

# Plot Feature Importance
plt.figure(figsize=(12, 7))
sns.barplot(x='importance', y='feature', data=feature_importance)
plt.title('Feature Importances from Random Forest Model')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()
